export const filters = [
  { label: 'All',        value: 'all',       icon: 'fa-solid fa-globe' },
  { label: 'Frontend',   value: 'frontend',  icon: 'fa-solid fa-screwdriver-wrench' },
  { label: 'Full Stack', value: 'fullstack', icon: 'fa-solid fa-code' },
  { label: 'E-commerce', value: 'ecommerce', icon: 'fa-solid fa-cart-shopping' },
]

export const projects = [
  {
    title: 'Love First Christian Center',
    category: 'fullstack',
    badge: 'Full Stack',
    image: 'https://www.khalstead.com/_astro/love-first.DAvA4NRL_ZM3WNo.webp',
    url: 'https://lfcc.tv',
    desc: 'Developed using Next.js 15. Features a custom CMS built with Sanity.io and integrates the Church Center API for seamless church management.',
    tags: ['Next.js', 'Sanity.io', 'API Integration'],
  },
  {
    title: 'Stone Savers',
    category: 'frontend',
    badge: 'Frontend',
    image: 'https://www.khalstead.com/_astro/stone-savers.CRwgA4Wf_1xYMl4.webp',
    url: 'https://stonesavers.us',
    desc: 'Static website experience created with SvelteKit. Includes Nodemailer functionality for efficient form submissions and a user-friendly interface.',
    tags: ['SvelteKit', 'Nodemailer', 'UI/UX'],
  },
  {
    title: 'Elite Web Wrxs',
    category: 'fullstack',
    badge: 'Full Stack',
    image: 'https://www.khalstead.com/_astro/elite-web-wrxs.B6KXA2Vy_Zb7xAj.webp',
    url: 'https://elitewebwrxs.com',
    desc: 'Dynamic website built with Next.js 14, utilizing Vercel Edge Functions, geolocation features, and Google Analytics for comprehensive tracking.',
    tags: ['Next.js', 'Edge Functions', 'Analytics'],
  },
  {
    title: 'How To Hear God',
    category: 'ecommerce',
    badge: 'E-commerce',
    image: 'https://www.khalstead.com/_astro/how-to-hear-god.C9ACkYbh_Z1NfxIn.webp',
    url: 'https://heargodbook.com',
    desc: 'Sales funnel built with Next.js 15, featuring Stripe for payments, ShipStation for fulfillment, and Kajabi API/webhook integration.',
    tags: ['Next.js', 'Stripe', 'E-commerce'],
  },
  {
    title: 'Road 2 Manhood',
    category: 'fullstack',
    badge: 'Full Stack',
    image: 'https://www.khalstead.com/_astro/road-2-manhood.Bb5sWjU8_Z14Efh6.webp',
    url: 'https://road2manhood.org',
    desc: 'Built with Next.js 15, Stripe, Sanity.io, and Nodemailer. A full-stack platform supporting a youth mentoring community.',
    tags: ['Next.js', 'Stripe', 'Sanity.io'],
  },
  {
    title: 'Max Transformation LLC',
    category: 'fullstack',
    badge: 'Full Stack',
    image: 'https://www.khalstead.com/_astro/max-transformation.BCtl3WTR_Z1Qr3eP.webp',
    url: 'https://maxtransformationllc.com',
    desc: 'Built with Next.js 15, Stripe, and Sanity.io. Features GSAP animations and Tailwind for a polished, modern interface.',
    tags: ['Next.js', 'Sanity.io', 'GSAP', 'Tailwind'],
  },
  {
    title: 'Gentle Phlebotomy',
    category: 'frontend',
    badge: 'Frontend',
    image: 'https://www.khalstead.com/_astro/gentle-phlebotomy.CPCGxiO4_Z1G8G1Z.webp',
    url: 'https://gentlephlebotomy.com',
    desc: 'Simple brochure site built with Astro. Calendly integrated for users to make appointments straight from the site.',
    tags: ['Astro', 'Nodemailer', 'Calendly'],
  },
  {
    title: 'Eagles Nest Conference',
    category: 'frontend',
    badge: 'Frontend',
    image: 'https://www.khalstead.com/_astro/eagles-nest.BCj-K0e8_Z1JtYiP.webp',
    url: 'https://eaglesnestconference.com',
    desc: 'Static brochure site built with Tailwind and Framer Motion to encourage engagement from users.',
    tags: ['Next.js', 'Tailwind', 'Framer Motion'],
  },
]